[fix]

diff --git a/package b/package
--- a/package
+++ b/package
@@ -48,7 +48,8 @@ clonemodule()
       if [ "$m" = "dune-fem" ]; then
         comHash=`git ls-remote ssh://git@gitlab.dune-project.org:22022/dune-fem/dune-fempy.git master | cut -f 1`
         if [ "$comHash" = "" ]; then
-            return 1
+            echo "could not retrieve hash for dune-fempy"
+            exit 1
         fi
         comStr="__pypi_dochash__ = "\"${comHash}\"
         sed -i -e "1i ${comStr}" python/dune/fem/__main__.py
